### ISSUE TITLE
Cant find the “Bake preparation Toolkit”  in the addon list

### ISSUE THREAD

**Issue by CometDY** [TR3D/SubstanceBakePrep#1]
Hello, thank you for sharing the nice Tool.
I've managed to install a zip file from the Preferences Addon, but the Bake Preparation Toolkit isn't showing up in the Addon list. 
Do you know what might be causing this? 
I'm using Blender 3.6.2.

**Comment by TR3D** [comment]
Hey,
I'll need to look into this but I suspect that something changed in python
API for this Blender version. This is going to take me a bit of time since
I don't have much freetime at the moment. Hope this is fine!

**Comment by TR3D** [comment]
Hey,
I just tested this with 3.6.2 and the addon shows up fine in the addon list. 
Can you try to download [this ](https://github.com/TR3D/SubstanceBakePrep/blob/main/src/BakePrepTool.py) file again and install it manually?

**Comment by CometDY** [comment]
Ah! It showing up correctly!
Thank you for dealing with it quickly!

**Comment by CometDY** [comment]
By the way, when combining models or reopening the scene , I get an error like this when toggling visibility on and off.
Do you know why this showing up?
![2023-12-18_14h30_19](https://github.com/TR3D/SubstanceBakePrep/assets/153900401/d1062c93-2909-4d87-842e-ca1aa4673adc)

**Comment by CometDY** [comment]
Python: Traceback (most recent call last):
  File "C:\Users\onepa\Downloads\blender-3.6.2-windows-x64\blender-3.6.2-windows-x64\3.6\scripts\addons\BakePrepTool.py", line 271, in execute
    toggle_hidden_meshes(self.unhide_low, self.unhide_high, False)
  File "C:\Users\onepa\Downloads\blender-3.6.2-windows-x64\blender-3.6.2-windows-x64\3.6\scripts\addons\BakePrepTool.py", line 522, in toggle_hidden_meshes
    item.hide_set(False)
ReferenceError: StructRNA of type Object has been removed

**Comment by CometDY** [comment]
it's a really fantastic tool, thank you so much! It's totally fine to take a look at it, if you're busy

**Comment by TR3D** [comment]
Glad that it works for you now!
I fear the error is caused by the way how i handle the references to the meshes. I'm not storing anything in the scene but rather only 'in the script'. The moment you reopen the scene, this information is lost. I'll put it on the list of possible improvements and try to tackle that when I have the time. Thanks for the input! 
Gonna mark this issue as 'resolved' then :)

**Comment by TR3D** [comment]
Hey @CometDY,
I just released a new version which allows you to save information about meshes in the Blender scene. This enables you to assign the low and high poly meshes to a 'bake set', save the scene and when reopening the scene, you are still able to work with these once you select the according bake set again. You should also be able to work with different sets in one Blender scene. Just download the latest release from [https://github.com/TR3D/SubstanceBakePrep/releases/tag/v1.0.0](url)
